### ISSUE TITLE
Confusion about sceneflow results of ACVNet and CGI-Stereo

### ISSUE THREAD

**Issue by Torment123** [gangweiX/ICG-Stereo#1]
Hi, thanks for the very insightful work of newly developed CGI module. While reading the paper, I found that in Table 2 it shows that on sceneflow, the EPE of ACVNet is 0.64, while the reported result in the ACV paper is 0.48, could you help me clarify which version of ACVNet this table is referring to? Thanks.

**Comment by gangweix** [comment]
I'm sorry for that. The results of 0.64 in Table 2 (CGI) is different from ACVNet. In Table 2, we only use ACV as the cost volume, and the other components of the network remain the same as CGI-Stereo. For example, we use the lighter mobilenet to extract features instead of Resnet,  and we also use a more lightweight cost aggregation network, which is more lightweight than ACVNet.

**Comment by Torment123** [comment]
Thanks for the clarification
